### ISSUE TITLE
Update index.ipynb

### ISSUE THREAD

**Issue by AustenLamacraft** [PyCav/Demos#23]
Would someone be able to update this? I guess it has to be done manually, unless someone can think of a cleverer way...

**Comment by jordanosborn** [comment]
I'm working on automating this

**Comment by jordanosborn** [comment]
index_generator.py will generate an index.ipynb file, it will include any ipynb files in the index that are in a sub directory and contain lines somewhere that read

#NAME: insert_example_name here

#DESCRIPTION: insert_description_here

Demos that exist just need to be updated to include these lines. And then the python script can be used to generate an index.ipynb file.

**Comment by jordanosborn** [comment]
New Index has been generated
